### ISSUE TITLE
Commenting feature does not work anymore

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#201]
The feature to comment on booking options is not available anymore. The setting can be configured in "Miscellaneous settings"

![Screenshot 2022-07-18 at 11-43-21 Editing Booking](https://user-images.githubusercontent.com/1620975/179485892-ec884a43-d3b0-4989-9933-a4d5580ab9eb.png)

Maybe the rating is also affected ;-).

**Comment by bernhard-wunderbyte** [comment]
Fixed in Booking 7.2.4 (2022071800) - Branch: main

**Comment by Sandrokkan** [comment]
Good morning,
in the currently available version the problem persists.

**Comment by bernhard-wunderbyte** [comment]
Fixed in Booking 7.0.22.15 - download at: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_39_STABLE.zip

@dasistwas Please publish the new version on Moodle.org

**Comment by dasistwas** [comment]
it is now released. https://moodle.org/plugins/mod_booking/v7.0.22.15/28316
