### ISSUE TITLE
Download table data does not work on Postgres

### ISSUE THREAD

**Issue by abias** [Wunderbyte-GmbH/moodle-mod_booking#76]
Hi David,

on your latest version of mod_booking (2017021500), where you brought back Postgres support, I encountered the following problem:

When downloading table data (no matter if I choose Excel, CSV or another format), I get this error:

Error reading from database

Debug info: ERROR: zero-length delimited identifier at or near """"
LINE 1: SELECT COUNT('x') FROM mdl_user WHERE idnumber <> ""
^
SELECT COUNT('x') FROM mdl_user WHERE idnumber <> ""
[array (
)]
Error code: dmlreadexception

Stack trace:
line 474 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 794 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1527 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 1600 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1810 of /lib/dml/moodle_database.php: call to moodle_database->get_field_sql()
line 1793 of /lib/dml/moodle_database.php: call to moodle_database->count_records_sql()
line 728 of /mod/booking/view.php: call to moodle_database->count_records_select()

Could you please check if you can fix this?

Thanks,
Alex

**Comment by abias** [comment]
PS: This might be a duplicate of issue #73, but I also get the error in activity instances where there are bookings from students.

**Comment by dasistwas** [comment]
Hi,
thank you for reporting this. Which database do you use?

Kind regards,
David

**Comment by dasistwas** [comment]
... sorry, I see the database in the stack trace: postgres. Alright.

**Comment by dasistwas** [comment]
Hi,

OK that was a problem with using double quotes instead of single quotes in SQL.

Fixed in 240e82a96d2456ca5d7d5e816c20bd886b710f15

Kind regards,
David

**Comment by abias** [comment]
Hi David,

I installed the latest version (which included your fix 240e82a), but the problem persists - on booking instances without bookings as well as on booking instances with bookings.

Thanks,
Alex

**Comment by dasistwas** [comment]
could you post the error message again?

**Comment by dasistwas** [comment]
Fixed in 4d2593db633747dea85537c895264f46b2fefbf9 
There was the same problem in another SQL query. I fixed that too.

**Comment by abias** [comment]
Hi David,

I can confirm that your second patch fixes the problem I described in this ticket. 
I would be grateful if you could upload the new version on moodle.org during the next days.

Thanks,
Alex

**Comment by dasistwas** [comment]
Hi Alex,

just uploaded the new version to moodle.org

Kind regards,
David

**Comment by abias** [comment]
Thanks, David!
