### ISSUE TITLE
Students can not book anymore (yellow disabled "warning" button labelled "book now")

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#917]
**Describe the bug**
No student enrolled in the course can book any options anymore. Admins and Managers can. This happened seemingly "spontaneously" without any changes being made. I updated to the current main version of Booking (20250307), but it stayed that way. I have checked and tried a few permissions, but the student role has "allow" for chose and view as always. No other role is set that could interfere. I found no debugging messages related to the issue. 

**Versions uses**
Moodle version: 4.4.1 (Build: 20240610)
Booking version: 8.10.6 (2025030701)

**Comment by bernhard-wunderbyte** [comment]
@VOOM108 Can you please check, if this also happens with our newest Booking version 8.11.4? You can get it here: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.11.4

We'll try to fix this asap if it still happens in this version.

**Comment by VOOM108** [comment]
Yes, it still happens. Any idea what might have caused it?

![Image](https://github.com/user-attachments/assets/a7ba3b3c-e560-4224-af62-64db1ffcd12c)

**Comment by bernhard-wunderbyte** [comment]
Can you have a look into your instance settings? For me it looks as if you have accidentally activated the setting "**Overwrite blocking warnings with text below**" (under "Advanced options"):

![Image](https://github.com/user-attachments/assets/8bb352d6-5d52-4b71-87da-2cdeeaa1e118)

**Comment by bernhard-wunderbyte** [comment]
If this is not the reason, please right click on the yellow warning buttons and inspect the HTML. What we need to investigate this further are the values of the data-results property.

It should look somehow like this:
`<div class="w-100 d-flex justify-content-center booking-button-area" data-itemid="1836" data-area="option" data-results="[-100,-90,-70,14]">`

**Comment by VOOM108** [comment]
```
<div class="booking-button-area noprice w-100" tabindex="0" data-itemid="7" data-componentname="mod_booking" data-area="option" data-userid="20022" data-results="[-100,-90,80]" data-nojs="1">
            <div class="booking-button-mainarea p-1 alert alert-warning w-100 text-center" role="alert">Book now</div>
</div>
```

**Comment by VOOM108** [comment]
I just removed a JS that changes some labels on buttons among other things, stuff that can not be changed with regular means. Now the button showed "Max number of bookings reached" for all bookings, even though, as can be seen in the screenshot above, they have not reached the set max. So I looked into the new settings to ignore passed and cancelled bookings in the limit for simultaneous bookings. Setting these to ignore made the bookings available again, as long as I keep the JS removed. I suppose things have changed in the HTML Structure and/or CSS that affect the script. So I need to look into that on my end, for now this issue is probably solved.

**Comment by VOOM108** [comment]
I just removed a JS that changes some labels on buttons among other things, stuff that can not be changed with regular means. Now the button showed "Max number of bookings reached" for all bookings. So I looked into the new settings to ignore passed and cancelled bookings regarding the limit for simultaneous bookings. 

There are several instances in the same course, with several options each. The options are exclusive inside the instance, thus in the instance max. 1 allowed is set. It looks for me, though, as if when any booked option in any of the instances exists for the user, they can not book in any of the instances anymore.

**Comment by VOOM108** [comment]
I checked some more users. It seems, the behavior that leads to these options being maxed out, is new. Because there are users who booked in two instances and those bookings are active. Still, the user now cannot book in any of the 18 instances.

**Comment by bernhard-wunderbyte** [comment]
@VOOM108 Thank you for finding this. You were right, we recently had a change which led to all bookings (system-wide) be counted instead of instance-specific bookings. Obviously, this was a bug. We fixed it within this version:

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.11.4-patch1

Can you install it and tell us if the issue is now fixed?

**Comment by bernhard-wunderbyte** [comment]
@georgmaisser You can rebase unit tests now onto MOODLE_401_DEV.

**Comment by VOOM108** [comment]
Thanks for the fix. It has gotten better, but there is still an issue: whenever there are several options in one instance, without an active or past booking in the instance, only the first option is bookable. The later ones again show the max message and are not bookable.

**Comment by bernhard-wunderbyte** [comment]
Please try again with this version: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.11.4-patch2

**Comment by VOOM108** [comment]
Looks good, thank you for the fast response and fix :)

**Comment by bernhard-wunderbyte** [comment]
No worries. I'll close this issue now.

**Comment by dasistwas** [comment]
@bernhard-wunderbyte do we have a test now that checks this behaviour?

**Comment by bernhard-wunderbyte** [comment]
@dasistwas I think @georgmaisser wrote a unit test that covers this now.
